// Action Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_CONTENT = 'GET_CONTENT';
export const GET_CONTENT_BY_ID = 'GET_CONTENT_BY_ID';
export const GET_CONTENT_BY_STRAND = 'GET_CONTENT_BY_STRAND';
export const GET_CONTENT_BY_TOPIC = 'GET_CONTENT_BY_TOPIC';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const CONTENT_ERROR = 'CONTENT_ERROR';
export const CLEAR_CONTENT = 'CLEAR_CONTENT';

export const GET_PROGRESS = 'GET_PROGRESS';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const GET_PROGRESS_REPORT = 'GET_PROGRESS_REPORT';
export const GET_SUGGESTIONS = 'GET_SUGGESTIONS';
export const PROGRESS_ERROR = 'PROGRESS_ERROR';

export const GET_TERMS = 'GET_TERMS';
export const CREATE_TERM = 'CREATE_TERM';
export const UPDATE_TERM = 'UPDATE_TERM';
export const GET_TERM_TOPICS = 'GET_TERM_TOPICS';
export const TERM_ERROR = 'TERM_ERROR';
